baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Polaroid archive'
theme = 'polaroid'

[[menus.main]]
name = 'Úvod'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Fotoaparáty'
pageRef = '/fotoaparaty'
weight = 2

[[menus.main]]
name = 'Filmy'
pageRef = '/filmy'
weight = 3

[[menus.main]]
name = 'Polaroidy'
pageRef = '/polaroidy'
weight = 4

[[menus.main]]
name = 'Ostatní'
pageRef = '/ostatní'
weight = 5

[[menus.main]]
name = 'Blog'
pageRef = '/Blog'
weight = 6